apiVersion: v1
kind: Pod
metadata:
  name: angular
  labels:
    app: angular
spec:
  containers:
    - name: angular
      image: gcr.io/starwars/swapi_webapp:v1
      ports:
        - containerPort: 80
